local function makeUndulateRange(from, peak_ratio)
  return function()
    return math.random(from, math.floor(from * peak_ratio + 0.5))
  end
end

local Constants = {
  WeaponExpTable = {
    wetgoop = makeUndulateRange(1, 2),
    spoiled_food = makeUndulateRange(1, 2),
    spear = makeUndulateRange(1, 2),
    torch = makeUndulateRange(1, 2),
    heatrock = makeUndulateRange(1, 2),
    bedroll_straw = makeUndulateRange(1, 2),
    spear_wathgrithr = makeUndulateRange(1, 2),
    wathgrithrhat = makeUndulateRange(1, 2),
    sewing_tape = makeUndulateRange(1, 2),
    saltrock = makeUndulateRange(1, 2),
    driftwood_log = makeUndulateRange(1, 2),
    spoiled_fish = makeUndulateRange(1, 2),
    spoiled_fish_small = makeUndulateRange(1, 2),
    rottenegg = makeUndulateRange(1, 2),
    ash = makeUndulateRange(1, 2),
    feather_crow = makeUndulateRange(1, 2),
    feather_robin = makeUndulateRange(1, 2),
    feather_robin_winter = makeUndulateRange(1, 2),
    silk = makeUndulateRange(1, 2),
    cutgrass = makeUndulateRange(1, 2),
    flint = makeUndulateRange(1, 2),
    rocks = makeUndulateRange(1, 2),
    nitre = makeUndulateRange(1, 2),
    log = makeUndulateRange(1, 2),
    twigs = makeUndulateRange(1, 2),
    monstermeat = makeUndulateRange(1, 2),
    poop = makeUndulateRange(1, 2),
    guano = makeUndulateRange(1, 2),
    boneshard = makeUndulateRange(1, 2),
    houndstooth = makeUndulateRange(1, 2),
    beardhair = makeUndulateRange(1, 2),
    fishmeat_small = makeUndulateRange(1, 2),
    smallmeat = makeUndulateRange(1, 2),
    cutlichen = makeUndulateRange(1, 2),
    cave_banana = makeUndulateRange(1, 2),
    acorn = makeUndulateRange(1, 2),
    pinecone = makeUndulateRange(1, 2),
    twiggy_nut = makeUndulateRange(1, 2),
    butterflywings = makeUndulateRange(1, 2),
    hambat = makeUndulateRange(2, 1.5),
    petals = makeUndulateRange(2, 1.5),
    marble = makeUndulateRange(2, 1.5),
    charcoal = makeUndulateRange(2, 1.5),
    meat = makeUndulateRange(2, 1.5),
    berries = makeUndulateRange(2, 1.5),
    berries_juicy = makeUndulateRange(2, 1.5),
    goatmilk = makeUndulateRange(2, 1.5),
    drumstick = makeUndulateRange(2, 1.5),
    froglegs = makeUndulateRange(2, 1.5),
    bird_egg = makeUndulateRange(2, 1.5),
    fishmeat = makeUndulateRange(2, 1.5),
    pigskin = makeUndulateRange(2, 1.5),
    manrabbit_tail = makeUndulateRange(2, 1.5),
    batwing = makeUndulateRange(2, 1.5),
    spidergland = makeUndulateRange(2, 1.5),
    furtuft = makeUndulateRange(2, 1.5),
    mosquitosack = makeUndulateRange(2, 1.5),
    sketch = makeUndulateRange(3, 1.66),
    tacklesketch = makeUndulateRange(3, 1.66),
    blueprint = makeUndulateRange(3, 1.66),
    nightstick = makeUndulateRange(3, 1.66),
    lightbulb = makeUndulateRange(3, 1.66),
    wormlight = makeUndulateRange(3, 1.66),
    wormlight_lesser = makeUndulateRange(3, 1.66),
    honeycomb = makeUndulateRange(3, 1.66),
    honey = makeUndulateRange(3, 1.66),
    stinger = makeUndulateRange(3, 1.66),
    cutreeds = makeUndulateRange(3, 1.66),
    coontail = makeUndulateRange(3, 1.66),
    gears = makeUndulateRange(3, 1.66),
    thulecite_pieces = makeUndulateRange(3, 1.66),
    glommerwings = makeUndulateRange(3, 1.66),
    glommerfuel = makeUndulateRange(3, 1.66),
    glommerflower = makeUndulateRange(3, 1.66),
    ice = makeUndulateRange(3, 1.66),
    tallbirdegg = makeUndulateRange(3, 1.66),
    plantmeat = makeUndulateRange(3, 1.66),
    gunpowder = makeUndulateRange(3, 1.66),
    goldnugget = makeUndulateRange(3, 1.66),
    beefalowool = makeUndulateRange(3, 1.66),
    seeds = makeUndulateRange(3, 1.66),
    boards = makeUndulateRange(4, 1.66),
    cutstone = makeUndulateRange(4, 1.66),
    whip = makeUndulateRange(4, 1.66),
    nightmarefuel = makeUndulateRange(4, 1.66),
    petals_evil = makeUndulateRange(4, 1.66),
    cactus_flower = makeUndulateRange(5, 1.66),
    livinglog = makeUndulateRange(5, 1.66),
    phlegm = makeUndulateRange(5, 1.66),
    spidereggsack = makeUndulateRange(5, 1.66),
    steelwool = makeUndulateRange(5, 1.66),
    feather_canary = makeUndulateRange(5, 1.66),
    tentaclespots = makeUndulateRange(5, 1.66),
    horn = makeUndulateRange(5, 1.66),
    lightninggoathorn = makeUndulateRange(5, 1.66),
    cookiecuttershell = makeUndulateRange(5, 1.66),
    slurper_pelt = makeUndulateRange(5, 1.66),
    cane = makeUndulateRange(5, 1.66),
    fig = makeUndulateRange(5, 1.66),
    transistor = makeUndulateRange(5, 1.66),
    boomerang = makeUndulateRange(5, 1.66),
    spore_small = makeUndulateRange(5, 1.66),
    spore_medium = makeUndulateRange(5, 1.66),
    spore_tall = makeUndulateRange(5, 1.66),
    papyrus = makeUndulateRange(6, 1.66),
    waxpaper = makeUndulateRange(6, 1.66),
    beeswax = makeUndulateRange(6, 1.66),
    slurtleslime = makeUndulateRange(6, 1.66),
    trunk_summer = makeUndulateRange(6, 1.66),
    trunk_winter = makeUndulateRange(6, 1.66),
    trunk_cooked = makeUndulateRange(6, 1.66),
    walrus_tusk = makeUndulateRange(6, 1.66),
    garlic = makeUndulateRange(6, 1.66),
    pepper = makeUndulateRange(6, 1.66),
    onion = makeUndulateRange(6, 1.66),
    potato = makeUndulateRange(6, 1.66),
    tomato = makeUndulateRange(6, 1.66),
    carrot = makeUndulateRange(6, 1.66),
    eggplant = makeUndulateRange(6, 1.66),
    corn = makeUndulateRange(6, 1.66),
    pumpkin = makeUndulateRange(6, 1.66),
    pomegranate = makeUndulateRange(6, 1.66),
    durian = makeUndulateRange(6, 1.66),
    dragonfruit = makeUndulateRange(6, 1.66),
    watermelon = makeUndulateRange(6, 1.66),
    panflute = makeUndulateRange(6, 1.66),
    redgem = makeUndulateRange(6, 50),
    bluegem = makeUndulateRange(6, 50),
    purplegem = makeUndulateRange(6, 50),
    greengem = makeUndulateRange(6, 50),
    orangegem = makeUndulateRange(6, 50),
    yellowgem = makeUndulateRange(6, 50),
    tentaclespike = makeUndulateRange(8, 1.66),
    reviver = makeUndulateRange(10, 1.5),
    healingsalve = makeUndulateRange(10, 1.5),
    corn_seeds = makeUndulateRange(10, 1.5),
    carrot_seeds = makeUndulateRange(10, 1.5),
    eggplant_seeds = makeUndulateRange(10, 1.5),
    pumpkin_seeds = makeUndulateRange(10, 1.5),
    pomegranate_seeds = makeUndulateRange(10, 1.5),
    durian_seeds = makeUndulateRange(10, 1.5),
    dragonfruit_seeds = makeUndulateRange(10, 1.5),
    watermelon_seeds = makeUndulateRange(10, 1.5),
    amulet = makeUndulateRange(10, 1.5),
    blowdart_pipe = makeUndulateRange(10, 1.5),
    blowdart_sleep = makeUndulateRange(10, 1.5),
    blowdart_fire = makeUndulateRange(10, 1.5),
    dug_grass = makeUndulateRange(10, 1.5),
    dug_sapling = makeUndulateRange(10, 1.5),
    dug_berrybush = makeUndulateRange(10, 1.5),
    dug_berrybush2 = makeUndulateRange(10, 1.5),
    dug_berrybush_juicy = makeUndulateRange(10, 1.5),
    dug_marsh_bush = makeUndulateRange(10, 1.5),
    dug_rock_avocado_bush = makeUndulateRange(10, 1.5),
    bandage = makeUndulateRange(12, 1.5),
    lifeinjector = makeUndulateRange(12, 1.5),
    orangeamulet = makeUndulateRange(12, 1.5),
    yellowamulet = makeUndulateRange(12, 1.5),
    greenamulet = makeUndulateRange(12, 1.5),
    blueamulet = makeUndulateRange(12, 1.5),
    purpleamulet = makeUndulateRange(12, 1.5),
    ratatouille = makeUndulateRange(12, 1.5),
    trailmix = makeUndulateRange(12, 1.5),
    flowersalad = makeUndulateRange(12, 1.5),
    guacamole = makeUndulateRange(12, 1.5),
    pumpkincookie = makeUndulateRange(12, 1.5),
    waffles = makeUndulateRange(12, 1.5),
    stuffedeggplant = makeUndulateRange(12, 1.5),
    jammypreserves = makeUndulateRange(12, 1.5),
    meatballs = makeUndulateRange(13, 1.5),
    kabobs = makeUndulateRange(13, 1.5),
    honeyham = makeUndulateRange(13, 1.5),
    honeynuggets = makeUndulateRange(13, 1.5),
    frogglebunwich = makeUndulateRange(13, 1.5),
    monsterlasagna = makeUndulateRange(13, 1.5),
    fishsticks = makeUndulateRange(13, 1.5),
    fishtacos = makeUndulateRange(13, 1.5),
    bonestew = makeUndulateRange(14, 1.5),
    dragonpie = makeUndulateRange(14, 1.5),
    butterflymuffin = makeUndulateRange(14, 1.5),
    powcake = makeUndulateRange(14, 1.5),
    fruitmedley = makeUndulateRange(14, 1.5),
    icecream = makeUndulateRange(14, 1.5),
    watermelonicle = makeUndulateRange(14, 1.5),
    jellybean = makeUndulateRange(14, 1.5),
    taffy = makeUndulateRange(14, 1.5),
    seafoodgumbo = makeUndulateRange(14, 1.5),
    surfnturf = makeUndulateRange(14, 1.5),
    lobsterbisque = makeUndulateRange(14, 1.5),
    lobsterdinner = makeUndulateRange(14, 1.5),
    frogfishbowl = makeUndulateRange(14, 1.5),
    moqueca = makeUndulateRange(14, 1.5),
    voltgoatjelly = makeUndulateRange(14, 1.5),
    bonesoup = makeUndulateRange(14, 1.5),
    unagi = makeUndulateRange(14, 1.5),
    turkeydinner = makeUndulateRange(14, 1.5),
    baconeggs = makeUndulateRange(14, 1.5),
    perogies = makeUndulateRange(14, 1.5),
    hotchili = makeUndulateRange(15, 1.5),
    blowdart_yellow = makeUndulateRange(15, 1.5),
    icestaff = makeUndulateRange(15, 1.5),
    firestaff = makeUndulateRange(15, 1.5),
    telestaff = makeUndulateRange(20, 1.5),
    orangestaff = makeUndulateRange(20, 1.5),
    staff_tornado = makeUndulateRange(20, 1.5),
    greenstaff = makeUndulateRange(20, 1.5),
    yellowstaff = makeUndulateRange(25, 1.5),
    opalstaff = makeUndulateRange(30, 1.5),
    fossil_piece = makeUndulateRange(35, 2),
    fossil_piece_clean = makeUndulateRange(35, 2),
    moonrocknugget = makeUndulateRange(40, 2),
    moonglass = makeUndulateRange(100, 2),
    thulecite = makeUndulateRange(100, 2),
    moonglass_charged = makeUndulateRange(140, 2),
    moonstorm_spark = makeUndulateRange(150, 2),
    moonstorm_glass = makeUndulateRange(160, 2),
    spiderhat = makeUndulateRange(180, 1.5),
    hivehat = makeUndulateRange(180, 1.5),
    royal_jelly = makeUndulateRange(200, 1.5),
    goose_feather = makeUndulateRange(200, 1.5),
    ruins_bat = makeUndulateRange(200, 1.5),
    ruinshat = makeUndulateRange(200, 1.5),
    armorruins = makeUndulateRange(200, 1.5),
    bearger_fur = makeUndulateRange(500, 2),
    mandrake = makeUndulateRange(500, 2.5),
    cookedmandrake = makeUndulateRange(510, 2.5),
    mandrakesoup = makeUndulateRange(550, 2.5),
    butter = makeUndulateRange(600, 2.5),
    deerclops_eyeball = makeUndulateRange(1000, 2),
    eyeturret_item = 1800,
    expbean = makeUndulateRange(2000, 4),
    dragon_scales = makeUndulateRange(2500, 2),
    shroom_skin = makeUndulateRange(3500, 2),
    malbatross_beak = makeUndulateRange(5000, 2),
    malbatross_feather = makeUndulateRange(5000, 2),
    minotaurhorn = makeUndulateRange(10000, 2),
    opalpreciousgem = makeUndulateRange(30000, 2),
    alterguardianhat = 300000
  },
  PickUpForbidPrefabs = {
    gift = true,
    bundle = true,
    spear = true,
    spear_wathgrithr = true,
    torch = true,
    axe = true,
    goldenaxe = true,
    pickaxe = true,
    goldenpickaxe = true,
    shovel = true,
    goldenshovel = true,
    hammer = true,
    multitool_axe_pickaxe = true,
    pitchfork = true,
    razor = true,
    featherpencil = true,
    fishingrod = true,
    oceanfishingrod = true,
    panflute = true,
    lantern = true,
    pumpkin_lantern = true,
    brush = true,
    farm_hoe = true,
    golden_farm_hoe = true,
    wateringcan = true,
    premiumwateringcan = true,
    tillweedsalve = true,
    seedpouch = true,
    compostingbin = true,
    plantregistryhat = true,
    nutrientsgoggleshat = true,
    trophyscale_oversizedveggies = true,
    book_horticulture = true,
    book_silviculture = true,
    fruitfly = true,
    lordfruitfly = true,
    friendlyfruitfly = true,
    fruitflyfruit = true,
    farm_soil_debris = true,
    soil_amender = true,
    soil_amender_fermented = true,
    compost = true,
    compostwrap = true,
    fertilizer = true,
    bugnet = true,
    trap = true,
    birdtrap = true,
    chester_eyebone = true,
    glommerflower = true,
    lavae_egg = true,
    lavae_cocoon = true,
    glommerfuel = true,
    horn = true,
    heatrock = true,
    -- flint = true,
    bedroll_straw = true,
    bedroll_furry = true,
    featherfan = true,
    tentaclespike = true,
    batbat = true,
    nightsword = true,
    ruins_bat = true,
    -- spidereggsack = true,
    wetgoop = true,
    spoiled_food = true,
    sketch = true,
    amulet = true,
    glommerwings = true,
    bernie_inactive = true,
    lighter = true,
    abigail_flower = true,
    lucy = true,
    reskin_tool = true,
    terrarium = true,
    tacklesketch = true,
    raincoat = true,
    sweatervest = true,
    reflectivevest = true,
    hawaiianshirt = true,
    beargervest = true,
    cane = true,
    mandrake = true,
    cookedmandrake = true,
    mandrakesoup = true,
    cookbook = true,
    fishingnet = true,
    mast_item = true,
    mast_malbatross_item = true,
    malbatross_feathered_weave = true,
    oar = true,
    oar_driftwood = true,
    miniflare = true,
    saltbox = true,
    saddlehorn = true,
    saddle_basic = true,
    reviver = true,
    diviningrod = true,
    grass_umbrella = true,
    umbrella = true,
    waterballoon = true,
    compass = true,
    onemanband = true,
    mapscroll = true,
    waxwelljournal = true,
    book_gardening = true,
    book_birds = true,
    book_sleep = true,
    book_tentacles = true,
    book_brimstone = true,
    thurible = true,
    saddle_war = true,
    saddle_race = true,
    trap_teeth = true,
    beemine = true,
    boomerang = true,
    trap_teeth_maxwell = true,
    beemine_maxwell = true,
    rock_avocado_fruit = true,
    rock_avocado_fruit_sprout = true,
    moonrockseed = true,
    bullkelp_beachedroot = true,
    beef_bell = true,
    moonrockidol = true,
    blueprint = true,
    tacklecontainer = true,
    supertacklecontainer = true,
  },
  PickUpForbidPattern = {
    "staff",
    "_tacklesketch",
    "_sketch",
    "deer_antler",
    "blowdart_",
    ".*hat$",
    "^armor.*",
    "trunkvest_",
    "oceanfishingbobber_",
    "_blueprint",
    "archive_lockbox",
    "container"
  },
  PickUpCanNotTags = {
    "FX",
    "INLIMBO",
    "NOCLICK",
    "knockbackdelayinteraction",
    "catchable",
    "fire",
    "minesprung",
    "mineactive",
    "spider",
    "tool",
    "weapon",
    "light"
  },
  -- 自动采摘 白名单
  PickPrefabs = {
    "sapling",
    "sapling_moon",
    -- "cactus",
    -- "oasis_cactus",
    "berrybush",
    "berrybush2",
    "berrybush_juicy",
    "grass",
    "reeds",
    "wormlight_plant",
    -- "marsh_bush",
    "flower_cave",
    "flower_cave_double",
    "flower_cave_triple",
    "stalker_bulb",
    "stalker_bulb_double",
    "carrot_planted",
    "cave_banana_tree",
    "cave_fern",
    "mandrake_planted",
    -- "red_mushroom",
    -- "green_mushroom",
    -- "blue_mushroom",
    "weed_firenettle",
    "weed_forgetmelots",
    "weed_ivy",
    "weed_tillweed"
  },
  SummonsList = {
    spider = 100.0,
    spider_hider = 20.0,
    spider_spitter = 50.0,
    spider_warrior = 30.0,
    spider_healer = 10.0,
    spider_dropper = 35.0,
    hound = 100.0,
    icehound = 20.0,
    tallbird = 10.0
    -- spiderqueen = 120.0
  },
  SummonsNicknameList = {
    spider = "小叽居",
    spider_hider = "龟缩叽居",
    spider_spitter = "吐网叽居",
    spider_warrior = "战斗叽居",
    spider_healer = "奶妈叽居",
    spider_dropper = "白脑壳叽居",
    hound = "小汪汪",
    icehound = "汪汪冰",
    tallbird = "长腿叽"
  }
}

local weight_total = 0
for _, value in pairs(Constants.SummonsList) do
  weight_total = weight_total + value
end
local acc = 0
for key, value in pairs(Constants.SummonsList) do
  local chance = value / weight_total
  Constants.SummonsList[key] = acc + chance
  acc = acc + chance
end

for num = 1, NUM_TRINKETS do
  Constants.WeaponExpTable["trinket_" .. tostring(num)] = function()
    return (TUNING.GOLD_VALUES.TRINKETS[num] or 3) * math.random(10, 50)
  end
end

setmetatable(
  Constants.WeaponExpTable,
  {
    __index = function(t, k)
      if string.match(k, ".*hat$") or string.match(k, "^armor.*") then
        return math.random(10, 50)
      end

      if string.match(k, ".*mooneye$") then
        return 50
      end

      if string.match(k, "^book_.*") then
        return 20
      end

      if string.match(k, "^wall.*item$") then
        return 15
      end

      if string.match(k, "^oceanfish_small_%d_inv$") then
        return math.random(120, 240)
      end

      if string.match(k, "^oceanfish_medium_%d_inv$") then
        return math.random(240, 480)
      end

      return math.random(1, 5) / 10
    end
  }
)

return Constants
